/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Inc/SysTick_interface.h"

int main(void)
{
	uint32_t Val;

	SysTick_u8ClkInit(AHB_DIV_8M, 6500);

	SysTick_u8ReadClkValue(&Val);

	SysTick_u8ClkControl(DISABLE);
    /* Loop forever */
	for(;;);
}
