/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "STATUS.h"

#include "RCC_interface.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	RCC_u8SetClockSrc(RCC_HSE_CLK, RCC_ON);
	RCC_u8HSEConfig(RCC_DIV_BY_2);

	RCC_u8SetSysClock(RCC_HSE_CLK);


	RCC_u8PLLConfig(RCC_PLL_MUL_10, RCC_HSE_CLK);

	RCC_u8PeripheralClkEnable(TIM1,RCC_APB2_CLK );
	RCC_u8PeripheralClkDisable(TIM1,RCC_APB2_CLK );

	uint8_t temp = RCC_u8GetSysClk();

    /* Loop forever */
	for(;;);
}
