/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Inc/STM32F103xx.h"
#include "../Inc/RCC_interface.h"
#include "../Inc/GPIO_interface.h"
int main(void)
{
	GPIO_PinConfig_T Pin1 =
	{
			.Port = PORTC,
			.PinNum = PIN13,
			.Mode = OUTPUT_50MHZ,
//			.PullType = PULL_UP,
			.InputOutConfig = GPO_PUSHPULL

	};
	RCC_u8PeripheralClkEnable(GPIOC_Per, RCC_APB2_CLK);
	GPIO_u8PinInit(&Pin1);

	GPIO_u8SetPinValue(Pin1.Port, Pin1.PinNum, PIN_HIGH);


//	GPIO_u8TogglePinValue(Pin1.Port, Pin1.PinNum);

    /* Loop forever */
	while(1)
	{

	}
}
