/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include "../Inc/RCC_interface.h"

int main(void)
{
	PLL_CONFG_T PLL_C;
	PLL_C.PLLMul = 80;
	PLL_C.PLL_M_Div = 4;
	PLL_C.PLL_P_Div = 4;
	PLL_C.PLL_R_Div = 3;
	PLL_C.PLL_Src = RCC_HSE_CLK;

	uint8_t temp = RCC_u8GetSysClk();

	RCC_u8SetClockSrc(RCC_HSE_CLK, RCC_ON);
	RCC_u8SetSysClock(RCC_HSE_CLK);
	RCC_u8PLLConfig(&PLL_C);
	RCC_u8PeripheralClkEnable(TIM10, RCC_APB2_CLK);
	RCC_u8PeripheralClkDisable(TIM10, RCC_APB2_CLK);
    /* Loop forever */
	for(;;);
}
