/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{


//	__asm volatile("MOV %0 , %1":"r"(var2):"i"(var1));

	/*Put the value 0x20001000 inside R1*/
//	__asm volatile("LDR R1, =#0x20001000");

//	/*Put the value 0x20001004 inside R2*/
//	__asm volatile("LDR R2, =#0x20001004");
//
//	/*Load Value from add in R1 inside R0 */
//	__asm volatile("LDR R0,[R1]");
//
//	/*Load Value from add in R2 inside R1 */
//	__asm volatile("LDR R1,[R2]");
//
//	/*Add Value inside  R1 and  R0 then store it inside R0*/
//	__asm volatile("ADD R0,R1");
//
//	/*Store result inside memory address stored inside R2*/
//	__asm volatile("STR R0,[R2]");

	int var = 20;

//	__asm volatile("MOV R0 , %0" : : "r"(var));
//	__asm volatile("MOV %1 , %0" :"=r"(var2):"i"(var1));


//	__asm volatile("MOV R0 , %0" : : "i"(0x50));

//	uint32_t CtrlReg = 20;
//	__asm volatile("MRS %0 , CONTROL" :"=r"(CtrlReg));

	int var1 = 50;
	int var2;

	/*Copy content of var1 into var2*/
	__asm volatile("MOV %0 , %0" :"=r"(var2):"r"(var1));


	int var3;
	uint32_t *ptr = (uint32_t *)0x20000008;
	*ptr = 30;
	/*Copy content of a pointer into var3*/
	__asm volatile("LDR R0 , [%0]"::"r"(ptr));
	__asm volatile("MOV %0 , R0":"=r"(var3));

	for(;;);
}
