/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ALIAS_BASE_ADD		0x22000000U
#define BIT_BAND_BASE_ADD	0x20000000U

int main(void)
{
	uint8_t *ptr = (uint8_t *)0x20000200;

	*ptr = 0xff;

	/*Normal method : clearing 7th bit position */
	*ptr &= ~(1<<7);

	/*Reset ptr*/
	*ptr = 0xff;

	/*Bit band method */
	uint8_t *AliasAdresss = (uint8_t *)(ALIAS_BASE_ADD + 7*4 + 32*((uint32_t )ptr - BIT_BAND_BASE_ADD));

	*AliasAdresss = 0;

	/* Loop forever */
	for(;;);
}
